name: backup-dev
on:
  workflow_dispatch:


jobs:
  
  create-leanix-backup:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version:  '3.9'
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run script
        run: python ./src/create_leanix_backup.py ${{ secrets.APITOKEN_DEV }} ${{ secrets.WORKSPACEID_DEV }} ${{ secrets.HOSTNAME }}


      - name: Artifact backup
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dev-backup
          path: ./src/backup/
